//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalkmeshVisualizerWpf.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowWalkableFaces {
            get {
                return ((bool)(this["ShowWalkableFaces"]));
            }
            set {
                this["ShowWalkableFaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowNonWalkableFaces {
            get {
                return ((bool)(this["ShowNonWalkableFaces"]));
            }
            set {
                this["ShowNonWalkableFaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowTransAbortPoints {
            get {
                return ((bool)(this["ShowTransAbortPoints"]));
            }
            set {
                this["ShowTransAbortPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowTransAbortRegions {
            get {
                return ((bool)(this["ShowTransAbortRegions"]));
            }
            set {
                this["ShowTransAbortRegions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowDefaultSpawnPoints {
            get {
                return ((bool)(this["ShowDefaultSpawnPoints"]));
            }
            set {
                this["ShowDefaultSpawnPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowLeftClickPointCoordinates {
            get {
                return ((bool)(this["ShowLeftClickPointCoordinates"]));
            }
            set {
                this["ShowLeftClickPointCoordinates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowRightClickPointCoordinates {
            get {
                return ((bool)(this["ShowRightClickPointCoordinates"]));
            }
            set {
                this["ShowRightClickPointCoordinates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowDlzLines {
            get {
                return ((bool)(this["ShowDlzLines"]));
            }
            set {
                this["ShowDlzLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowDoorsOnAddRim {
            get {
                return ((bool)(this["ShowDoorsOnAddRim"]));
            }
            set {
                this["ShowDoorsOnAddRim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowTriggersOnAddRim {
            get {
                return ((bool)(this["ShowTriggersOnAddRim"]));
            }
            set {
                this["ShowTriggersOnAddRim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowEncountersOnAddRim {
            get {
                return ((bool)(this["ShowEncountersOnAddRim"]));
            }
            set {
                this["ShowEncountersOnAddRim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowLivePosition {
            get {
                return ((bool)(this["ShowLivePosition"]));
            }
            set {
                this["ShowLivePosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowLivePositionCoordinates {
            get {
                return ((bool)(this["ShowLivePositionCoordinates"]));
            }
            set {
                this["ShowLivePositionCoordinates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ViewFollowsLivePosition {
            get {
                return ((bool)(this["ViewFollowsLivePosition"]));
            }
            set {
                this["ViewFollowsLivePosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowCurrentLiveModule {
            get {
                return ((bool)(this["ShowCurrentLiveModule"]));
            }
            set {
                this["ShowCurrentLiveModule"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HidePreviousLiveModule {
            get {
                return ((bool)(this["HidePreviousLiveModule"]));
            }
            set {
                this["HidePreviousLiveModule"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HotswapToLiveGame {
            get {
                return ((bool)(this["HotswapToLiveGame"]));
            }
            set {
                this["HotswapToLiveGame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int LivePositionUpdateDelay {
            get {
                return ((int)(this["LivePositionUpdateDelay"]));
            }
            set {
                this["LivePositionUpdateDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowRimDataUnderMouse {
            get {
                return ((bool)(this["ShowRimDataUnderMouse"]));
            }
            set {
                this["ShowRimDataUnderMouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowGatherPartyRange {
            get {
                return ((bool)(this["ShowGatherPartyRange"]));
            }
            set {
                this["ShowGatherPartyRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowCoordinatePanel {
            get {
                return ((bool)(this["ShowCoordinatePanel"]));
            }
            set {
                this["ShowCoordinatePanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowRimDataPanel {
            get {
                return ((bool)(this["ShowRimDataPanel"]));
            }
            set {
                this["ShowRimDataPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("304")]
        public double PrevLeftPanelSize {
            get {
                return ((double)(this["PrevLeftPanelSize"]));
            }
            set {
                this["PrevLeftPanelSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("315")]
        public double PrevRightPanelSize {
            get {
                return ((double)(this["PrevRightPanelSize"]));
            }
            set {
                this["PrevRightPanelSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowWalkmeshPanel {
            get {
                return ((bool)(this["ShowWalkmeshPanel"]));
            }
            set {
                this["ShowWalkmeshPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowLeftClickGatherPartyRange {
            get {
                return ((bool)(this["ShowLeftClickGatherPartyRange"]));
            }
            set {
                this["ShowLeftClickGatherPartyRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowDistancePanel {
            get {
                return ((bool)(this["ShowDistancePanel"]));
            }
            set {
                this["ShowDistancePanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowToolsPanel {
            get {
                return ((bool)(this["ShowToolsPanel"]));
            }
            set {
                this["ShowToolsPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bright")]
        public string SelectedPaletteName {
            get {
                return ((string)(this["SelectedPaletteName"]));
            }
            set {
                this["SelectedPaletteName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowRimDataDoors {
            get {
                return ((bool)(this["ShowRimDataDoors"]));
            }
            set {
                this["ShowRimDataDoors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowRimDataTriggers {
            get {
                return ((bool)(this["ShowRimDataTriggers"]));
            }
            set {
                this["ShowRimDataTriggers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowRimDataTraps {
            get {
                return ((bool)(this["ShowRimDataTraps"]));
            }
            set {
                this["ShowRimDataTraps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowRimDataZones {
            get {
                return ((bool)(this["ShowRimDataZones"]));
            }
            set {
                this["ShowRimDataZones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowRimDataEncounters {
            get {
                return ((bool)(this["ShowRimDataEncounters"]));
            }
            set {
                this["ShowRimDataEncounters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SelectedBackgroundColor {
            get {
                return ((int)(this["SelectedBackgroundColor"]));
            }
            set {
                this["SelectedBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTypeUnderMouse {
            get {
                return ((bool)(this["ShowTypeUnderMouse"]));
            }
            set {
                this["ShowTypeUnderMouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowResRefUnderMouse {
            get {
                return ((bool)(this["ShowResRefUnderMouse"]));
            }
            set {
                this["ShowResRefUnderMouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTagUnderMouse {
            get {
                return ((bool)(this["ShowTagUnderMouse"]));
            }
            set {
                this["ShowTagUnderMouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowLocalizedNameUnderMouse {
            get {
                return ((bool)(this["ShowLocalizedNameUnderMouse"]));
            }
            set {
                this["ShowLocalizedNameUnderMouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowOnEnterUnderMouse {
            get {
                return ((bool)(this["ShowOnEnterUnderMouse"]));
            }
            set {
                this["ShowOnEnterUnderMouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowTrapsOnAddRim {
            get {
                return ((bool)(this["ShowTrapsOnAddRim"]));
            }
            set {
                this["ShowTrapsOnAddRim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowZonesOnAddRim {
            get {
                return ((bool)(this["ShowZonesOnAddRim"]));
            }
            set {
                this["ShowZonesOnAddRim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowWireTargetPanel {
            get {
                return ((bool)(this["ShowWireTargetPanel"]));
            }
            set {
                this["ShowWireTargetPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowGlobalsPanel {
            get {
                return ((bool)(this["ShowGlobalsPanel"]));
            }
            set {
                this["ShowGlobalsPanel"] = value;
            }
        }
    }
}
