<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <AssemblyName>WalkmeshVisualizer</AssemblyName>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
	<VersionPrefix>2.0.14</VersionPrefix>
	<Title>WalkmeshVisualizerWpf</Title>
	<Copyright>2026</Copyright>
	<ApplicationIcon>Resources\Icons\Icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Resources\Icons\Backspace.png" />
    <None Remove="Resources\Icons\Edit.png" />
    <None Remove="Resources\Icons\Filter.png" />
    <None Remove="Resources\Icons\PopupIcon.png" />
    <None Remove="Resources\Icons\RemoveIcon.png" />
    <None Remove="Resources\Icons\Save.png" />
    <None Remove="Resources\Icons\TimerIcon.png" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="KotorMessageInjector">
      <HintPath>..\..\KotorMessageInjector\KotorMessageInjector\bin\Debug\netstandard2.0\KotorMessageInjector.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="KotOR_IO">
      <HintPath>..\..\KotOR_IO\KotOR_IO\bin\Debug\net8.0\KotOR_IO.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="Resources\Palettes\Baby.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Palettes\Bright.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Palettes\ElectroPunk.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Palettes\ExtraBright.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Palettes\Muted.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Palettes\Pastel.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Palettes\Rainbow.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Palettes\Spring.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Palettes\TreeLights.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Icons\Backspace.png" />
    <Resource Include="Resources\Icons\Edit.png" />
    <Resource Include="Resources\Icons\Filter.png" />
    <Resource Include="Resources\Icons\PopupIcon.png" />
    <Resource Include="Resources\Icons\RefreshIcon.png" />
    <Resource Include="Resources\Icons\AddIcon.png" />
    <Resource Include="Resources\Icons\ClearIcon.png" />
    <Resource Include="Resources\Icons\OptionsIcon.png" />
    <Resource Include="Resources\Icons\FolderIcon.png" />
    <Resource Include="Resources\Icons\RemoveIcon.png" />
    <Resource Include="Resources\Icons\Save.png" />
    <Resource Include="Resources\Icons\TimerIcon.png" />
    <Resource Include="Resources\Icons\UndoIcon.png" />
    <Resource Include="Resources\Icons\GatherPartyRangeLeftClickIcon.png" />
    <Resource Include="Resources\Icons\GatherPartyRangeLockIcon.png" />
    <Resource Include="Resources\Icons\GatherPartyRangeIcon.png" />
    <Resource Include="Resources\Icons\MouseHoverIcon.png" />
    <Resource Include="Resources\Icons\HotswapIcon.png" />
    <Resource Include="Resources\Icons\ViewFollowsLivePositionIcon.png" />
    <Resource Include="Resources\Icons\HidePreviousModuleIcon.png" />
    <Resource Include="Resources\Icons\ShowCurrentModuleIcon.png" />
    <Resource Include="Resources\Icons\LivePositionIcon.png" />
    <Resource Include="Resources\Icons\DefaultSpawnPointIcon.png" />
    <Resource Include="Resources\Icons\DisplacedLoadingZoneIcon.png" />
    <Content Include="Resources\Data\DlzData.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Resource Include="Resources\Icons\Icon.ico" />
    <Resource Include="Resources\Icons\DlzIcon.png" />
    <Content Include="Resources\Data\GameData.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Resource Include="Resources\Icons\GatherPartyRegionIcon.png" />
    <Resource Include="Resources\Icons\NonWalkIcon.png" />
    <Resource Include="Resources\Icons\WalkIcon.png" />
    <Resource Include="Resources\Icons\GatherPartyIcon.png" />
    <Resource Include="Resources\Icons\TransAbortsAlpha.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Icons\Icon.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZoomAndPan\ZoomAndPan.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>